<?php

use Illuminate\Database\Seeder;
use DigitalFormula\Country;

class CountryTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $prefix = Config::get( 'database.connections.mysql.prefix' );
        \DB::table( 'countries' )->truncate();

        $country_list = array(
            array( 'slug' => 'AD', 'name' => 'Andorra', 'currency' => 'EUR' ),
            array( 'slug' => 'AE', 'name' => 'United Arab Emirates', 'currency' => 'AED' ),
            array( 'slug' => 'AF', 'name' => 'Afghanistan', 'currency' => 'AFN' ),
            array( 'slug' => 'AG', 'name' => 'Antigua and Barbuda', 'currency' => 'XCD' ),
            array( 'slug' => 'AI', 'name' => 'Anguilla', 'currency' => 'XCD' ),
            array( 'slug' => 'AL', 'name' => 'Albania', 'currency' => 'ALL' ),
            array( 'slug' => 'AM', 'name' => 'Armenia', 'currency' => 'AMD' ),
            array( 'slug' => 'AO', 'name' => 'Angola', 'currency' => 'AOA' ),
            array( 'slug' => 'AQ', 'name' => 'Antarctica', 'currency' => '-' ),
            array( 'slug' => 'AR', 'name' => 'Argentina', 'currency' => 'ARS' ),
            array( 'slug' => 'AS', 'name' => 'American Samoa', 'currency' => 'USD' ),
            array( 'slug' => 'AT', 'name' => 'Austria', 'currency' => 'EUR' ),
            array( 'slug' => 'AU', 'name' => 'Australia', 'currency' => 'AUD' ),
            array( 'slug' => 'AW', 'name' => 'Aruba', 'currency' => 'AWG' ),
            array( 'slug' => 'AX', 'name' => 'Aland Islands', 'currency' => 'EUR' ),
            array( 'slug' => 'AZ', 'name' => 'Azerbaijan', 'currency' => 'AZN' ),
            array( 'slug' => 'BA', 'name' => 'Bosnia and Herzegovina', 'currency' => 'BAM' ),
            array( 'slug' => 'BB', 'name' => 'Barbados', 'currency' => 'BBD' ),
            array( 'slug' => 'BD', 'name' => 'Bangladesh', 'currency' => 'BDT' ),
            array( 'slug' => 'BE', 'name' => 'Belgium', 'currency' => 'EUR' ),
            array( 'slug' => 'BF', 'name' => 'Burkina Faso', 'currency' => 'XOF' ),
            array( 'slug' => 'BG', 'name' => 'Bulgaria', 'currency' => 'BGN' ),
            array( 'slug' => 'BH', 'name' => 'Bahrain', 'currency' => 'BHD' ),
            array( 'slug' => 'BI', 'name' => 'Burundi', 'currency' => 'BIF' ),
            array( 'slug' => 'BJ', 'name' => 'Benin', 'currency' => 'XOF' ),
            array( 'slug' => 'BL', 'name' => 'Saint Barthelemy', 'currency' => 'EUR' ),
            array( 'slug' => 'BM', 'name' => 'Bermuda', 'currency' => 'BMD' ),
            array( 'slug' => 'BN', 'name' => 'Brunei Darussalam', 'currency' => 'BND' ),
            array( 'slug' => 'BO', 'name' => 'Bolivia', 'currency' => 'BOB' ),
            array( 'slug' => 'BQ', 'name' => 'Bonaire, Saint Eustatius and Saba', 'currency' => 'USD' ),
            array( 'slug' => 'BR', 'name' => 'Brazil', 'currency' => 'BRL' ),
            array( 'slug' => 'BS', 'name' => 'Bahamas', 'currency' => 'BSD' ),
            array( 'slug' => 'BT', 'name' => 'Bhutan', 'currency' => 'BTN' ),
            array( 'slug' => 'BW', 'name' => 'Botswana', 'currency' => 'BWP' ),
            array( 'slug' => 'BY', 'name' => 'Belarus', 'currency' => 'BYR' ),
            array( 'slug' => 'BZ', 'name' => 'Beliz', 'currency' => 'BZD' ),
            array( 'slug' => 'CA', 'name' => 'Canada', 'currency' => 'CAD' ),
            array( 'slug' => 'CD', 'name' => 'Congo, The Democratic Republic of the', 'currency' => 'CDF' ),
            array( 'slug' => 'CF', 'name' => 'Central African Republic', 'currency' => 'XAF' ),
            array( 'slug' => 'CG', 'name' => 'Congo', 'currency' => 'CDF' ),
            array( 'slug' => 'CH', 'name' => 'Switzerland', 'currency' => 'CHF' ),
            array( 'slug' => 'CI', 'name' => 'Cote D\'Ivoire', 'currency' => 'XOF' ),
            array( 'slug' => 'CK', 'name' => 'Cook Islands', 'currency' => 'NZD' ),
            array( 'slug' => 'CL', 'name' => 'Chile', 'currency' => 'CLP' ),
            array( 'slug' => 'CM', 'name' => 'Cameroon', 'currency' => 'XAF' ),
            array( 'slug' => 'CN', 'name' => 'China', 'currency' => 'CNY' ),
            array( 'slug' => 'CO', 'name' => 'Colombia', 'currency' => 'COP' ),
            array( 'slug' => 'CR', 'name' => 'Costa Rica', 'currency' => 'COP' ),
            array( 'slug' => 'CU', 'name' => 'Cuba', 'currency' => 'CUP' ),
            array( 'slug' => 'CV', 'name' => 'Cape Verde', 'currency' => 'CVE' ),
            array( 'slug' => 'CW', 'name' => 'Curacao', 'currency' => 'ANG' ),
            array( 'slug' => 'CY', 'name' => 'Cyprus', 'currency' => 'EUR' ),
            array( 'slug' => 'CZ', 'name' => 'Czech Republic', 'currency' => 'CZK' ),
            array( 'slug' => 'DE', 'name' => 'Germany', 'currency' => 'EUR' ),
            array( 'slug' => 'DJ', 'name' => 'Djibouti', 'currency' => 'DJF' ),
            array( 'slug' => 'DK', 'name' => 'Denmark', 'currency' => 'DKK' ),
            array( 'slug' => 'DM', 'name' => 'Dominica', 'currency' => 'XCD' ),
            array( 'slug' => 'DO', 'name' => 'Dominican Republic', 'currency' => 'DOP' ),
            array( 'slug' => 'DZ', 'name' => 'Algeria', 'currency' => 'DZD' ),
            array( 'slug' => 'EC', 'name' => 'Ecuador', 'currency' => 'USD' ),
            array( 'slug' => 'EE', 'name' => 'Estonia', 'currency' => 'EUR' ),
            array( 'slug' => 'EG', 'name' => 'Egypt', 'currency' => 'EGP' ),
            array( 'slug' => 'ER', 'name' => 'Eritrea', 'currency' => 'ERN' ),
            array( 'slug' => 'ES', 'name' => 'Spain', 'currency' => 'EUR' ),
            array( 'slug' => 'ET', 'name' => 'Ethiopia', 'currency' => 'ETB' ),
            array( 'slug' => 'EU', 'name' => 'Europe', 'currency' => 'EUR' ),
            array( 'slug' => 'FI', 'name' => 'Finland', 'currency' => 'EUR' ),
            array( 'slug' => 'FJ', 'name' => 'Fiji', 'currency' => 'FJD' ),
            array( 'slug' => 'FK', 'name' => 'Falkland Islands (Malvinas)', 'currency' => 'FKP' ),
            array( 'slug' => 'FM', 'name' => 'Micronesia, Federated States of', 'currency' => 'USD' ),
            array( 'slug' => 'FO', 'name' => 'Faroe Islands', 'currency' => 'DKK' ),
            array( 'slug' => 'FR', 'name' => 'France', 'currency' => 'EUR' ),
            array( 'slug' => 'GA', 'name' => 'Gabon', 'currency' => 'XAF' ),
            array( 'slug' => 'GB', 'name' => 'United Kingdom', 'currency' => 'GBP' ),
            array( 'slug' => 'GD', 'name' => 'Grenada', 'currency' => 'XCD' ),
            array( 'slug' => 'GE', 'name' => 'Georgia', 'currency' => 'GEL' ),
            array( 'slug' => 'GF', 'name' => 'French Guiana', 'currency' => 'EUR' ),
            array( 'slug' => 'GG', 'name' => 'Guernsey', 'currency' => 'GGP' ),
            array( 'slug' => 'GH', 'name' => 'Ghana', 'currency' => 'GHS' ),
            array( 'slug' => 'GI', 'name' => 'Gibraltar', 'currency' => 'GIP' ),
            array( 'slug' => 'GL', 'name' => 'Greenland', 'currency' => 'DKK' ),
            array( 'slug' => 'GM', 'name' => 'Gambia', 'currency' => 'GMD' ),
            array( 'slug' => 'GN', 'name' => 'Guinea', 'currency' => 'GNF' ),
            array( 'slug' => 'GP', 'name' => 'Guadeloupe', 'currency' => 'EUR' ),
            array( 'slug' => 'GQ', 'name' => 'Equatorial Guinea', 'currency' => 'XAF' ),
            array( 'slug' => 'GR', 'name' => 'Greece', 'currency' => 'EUR' ),
            array( 'slug' => 'GT', 'name' => 'Guatemala', 'currency' => 'GTQ' ),
            array( 'slug' => 'GU', 'name' => 'Guam', 'currency' => 'USD' ),
            array( 'slug' => 'GW', 'name' => 'Guinea-Bissau', 'currency' => 'XOF' ),
            array( 'slug' => 'GY', 'name' => 'Guyana', 'currency' => 'GYD' ),
            array( 'slug' => 'HK', 'name' => 'Hong Kong', 'currency' => 'HKD' ),
            array( 'slug' => 'HN', 'name' => 'Honduras', 'currency' => 'HNL' ),
            array( 'slug' => 'HR', 'name' => 'Croatia', 'currency' => 'HRK' ),
            array( 'slug' => 'HT', 'name' => 'Haiti', 'currency' => 'HTG' ),
            array( 'slug' => 'HU', 'name' => 'Hungary', 'currency' => 'HUF' ),
            array( 'slug' => 'ID', 'name' => 'Indonesia', 'currency' => 'IDR' ),
            array( 'slug' => 'IE', 'name' => 'Ireland', 'currency' => 'EUR' ),
            array( 'slug' => 'IL', 'name' => 'Israel', 'currency' => 'ILS' ),
            array( 'slug' => 'IM', 'name' => 'Isle of Man', 'currency' => 'IMP' ),
            array( 'slug' => 'IN', 'name' => 'India', 'currency' => 'INR' ),
            array( 'slug' => 'IO', 'name' => 'British Indian Ocean Territory', 'currency' => 'USD' ),
            array( 'slug' => 'IP', 'name' => 'Clipperton Island', 'currency' => '-' ),
            array( 'slug' => 'IQ', 'name' => 'Iraq', 'currency' => 'IQD' ),
            array( 'slug' => 'IR', 'name' => 'Iran, Islamic Republic of', 'currency' => 'IRR' ),
            array( 'slug' => 'IS', 'name' => 'Iceland', 'currency' => 'ISK' ),
            array( 'slug' => 'IT', 'name' => 'Italy', 'currency' => 'EUR' ),
            array( 'slug' => 'JE', 'name' => 'Jersey', 'currency' => 'JEP' ),
            array( 'slug' => 'JM', 'name' => 'Jamaica', 'currency' => 'JMD' ),
            array( 'slug' => 'JO', 'name' => 'Jordan', 'currency' => 'JOD' ),
            array( 'slug' => 'JP', 'name' => 'Japan', 'currency' => 'JPY' ),
            array( 'slug' => 'KE', 'name' => 'Kenya', 'currency' => 'KES' ),
            array( 'slug' => 'KG', 'name' => 'Kyrgyzstan', 'currency' => 'KGS' ),
            array( 'slug' => 'KH', 'name' => 'Cambodia', 'currency' => 'KHR' ),
            array( 'slug' => 'KI', 'name' => 'Kiribati', 'currency' => 'AUD' ),
            array( 'slug' => 'KM', 'name' => 'Comoros', 'currency' => 'KMF' ),
            array( 'slug' => 'KN', 'name' => 'Saint Kitts and Nevis', 'currency' => 'XCD' ),
            array( 'slug' => 'KP', 'name' => 'Korea, Democratic People\'s Republic of', 'currency' => 'KRW' ),
            array( 'slug' => 'KR', 'name' => 'Korea, Republic of', 'currency' => 'KPW' ),
            array( 'slug' => 'KW', 'name' => 'Kuwait', 'currency' => 'KWD' ),
            array( 'slug' => 'KY', 'name' => 'Cayman Islands', 'currency' => 'KYD' ),
            array( 'slug' => 'KZ', 'name' => 'Kazakhstan', 'currency' => 'KZT' ),
            array( 'slug' => 'LA', 'name' => 'Lao People\'s Democratic Republic', 'currency' => 'LAK' ),
            array( 'slug' => 'LB', 'name' => 'Lebanon', 'currency' => 'LBP' ),
            array( 'slug' => 'LC', 'name' => 'Saint Lucia', 'currency' => 'XCD' ),
            array( 'slug' => 'LI', 'name' => 'Liechtenstein', 'currency' => 'CHF' ),
            array( 'slug' => 'LK', 'name' => 'Sri Lanka', 'currency' => 'LKR' ),
            array( 'slug' => 'LR', 'name' => 'Liberia', 'currency' => 'LRD' ),
            array( 'slug' => 'LS', 'name' => 'Lesotho', 'currency' => 'LSL' ),
            array( 'slug' => 'LT', 'name' => 'Lithuania', 'currency' => 'LTL' ),
            array( 'slug' => 'LU', 'name' => 'Luxembourg', 'currency' => 'EUR' ),
            array( 'slug' => 'LV', 'name' => 'Latvia', 'currency' => 'LVL' ),
            array( 'slug' => 'LY', 'name' => 'Libya', 'currency' => 'LYD' ),
            array( 'slug' => 'MA', 'name' => 'Morocco', 'currency' => 'MAD' ),
            array( 'slug' => 'MC', 'name' => 'Monaco', 'currency' => 'EUR' ),
            array( 'slug' => 'MD', 'name' => 'Moldova, Republic of', 'currency' => 'MDL' ),
            array( 'slug' => 'ME', 'name' => 'Montenegro', 'currency' => 'EUR' ),
            array( 'slug' => 'MF', 'name' => 'Saint Martin', 'currency' => 'NLG' ),
            array( 'slug' => 'MG', 'name' => 'Madagascar', 'currency' => 'MGA' ),
            array( 'slug' => 'MH', 'name' => 'Marshall Islands', 'currency' => 'USD' ),
            array( 'slug' => 'MK', 'name' => 'Macedonia', 'currency' => 'MKD' ),
            array( 'slug' => 'ML', 'name' => 'Mali', 'currency' => 'XOF' ),
            array( 'slug' => 'MM', 'name' => 'Myanmar', 'currency' => 'MMK' ),
            array( 'slug' => 'MN', 'name' => 'Mongolia', 'currency' => 'MNT' ),
            array( 'slug' => 'MO', 'name' => 'Macau', 'currency' => 'MOP' ),
            array( 'slug' => 'MP', 'name' => 'Northern Mariana Islands', 'currency' => 'USD' ),
            array( 'slug' => 'MQ', 'name' => 'Martinique', 'currency' => 'EUR' ),
            array( 'slug' => 'MR', 'name' => 'Mauritania', 'currency' => 'MRO' ),
            array( 'slug' => 'MS', 'name' => 'Montserrat', 'currency' => 'XCD' ),
            array( 'slug' => 'MT', 'name' => 'Malta', 'currency' => 'EUR' ),
            array( 'slug' => 'MU', 'name' => 'Mauritius', 'currency' => 'MUR' ),
            array( 'slug' => 'MV', 'name' => 'Maldives', 'currency' => 'MVR' ),
            array( 'slug' => 'MW', 'name' => 'Malawi', 'currency' => 'MWK' ),
            array( 'slug' => 'MX', 'name' => 'Mexico', 'currency' => 'MXN' ),
            array( 'slug' => 'MY', 'name' => 'Malaysia', 'currency' => 'MYR' ),
            array( 'slug' => 'MZ', 'name' => 'Mozambique', 'currency' => 'MZN' ),
            array( 'slug' => 'NA', 'name' => 'Namibia', 'currency' => 'NAD' ),
            array( 'slug' => 'NC', 'name' => 'New Caledonia', 'currency' => 'XPF' ),
            array( 'slug' => 'NE', 'name' => 'Niger', 'currency' => 'XOF' ),
            array( 'slug' => 'NF', 'name' => 'Norfolk Island', 'currency' => 'AUD' ),
            array( 'slug' => 'NG', 'name' => 'Nigeria', 'currency' => 'NGN' ),
            array( 'slug' => 'NI', 'name' => 'Nicaragua', 'currency' => 'NIO' ),
            array( 'slug' => 'NL', 'name' => 'Netherlands', 'currency' => 'EUR' ),
            array( 'slug' => 'NO', 'name' => 'Norway', 'currency' => 'NOK' ),
            array( 'slug' => 'NP', 'name' => 'Nepal', 'currency' => 'NPR' ),
            array( 'slug' => 'NR', 'name' => 'Nauru', 'currency' => 'AUD' ),
            array( 'slug' => 'NU', 'name' => 'Niue', 'currency' => 'NZD' ),
            array( 'slug' => 'NZ', 'name' => 'New Zealand', 'currency' => 'NZD' ),
            array( 'slug' => 'OM', 'name' => 'Oman', 'currency' => 'OMR' ),
            array( 'slug' => 'PA', 'name' => 'Panama', 'currency' => 'PAB' ),
            array( 'slug' => 'PE', 'name' => 'Peru', 'currency' => 'PEN' ),
            array( 'slug' => 'PF', 'name' => 'French Polynesia', 'currency' => 'XPF' ),
            array( 'slug' => 'PG', 'name' => 'Papua New Guinea', 'currency' => 'PGK' ),
            array( 'slug' => 'PH', 'name' => 'Philippines', 'currency' => 'PHP' ),
            array( 'slug' => 'PK', 'name' => 'Pakistan', 'currency' => 'PKR' ),
            array( 'slug' => 'PL', 'name' => 'Poland', 'currency' => 'PLN' ),
            array( 'slug' => 'PM', 'name' => 'Saint Pierre and Miquelon', 'currency' => 'EUR' ),
            array( 'slug' => 'PN', 'name' => 'Pitcairn Islands', 'currency' => 'NZD' ),
            array( 'slug' => 'PR', 'name' => 'Puerto Rico', 'currency' => 'USD' ),
            array( 'slug' => 'PS', 'name' => 'Palestinian Territory', 'currency' => 'ILS' ),
            array( 'slug' => 'PT', 'name' => 'Portugal', 'currency' => 'EUR' ),
            array( 'slug' => 'PW', 'name' => 'Palau', 'currency' => 'USD' ),
            array( 'slug' => 'PY', 'name' => 'Paraguay', 'currency' => 'PYG' ),
            array( 'slug' => 'QA', 'name' => 'Qatar', 'currency' => 'QAR' ),
            array( 'slug' => 'RE', 'name' => 'Reunion', 'currency' => 'EUR' ),
            array( 'slug' => 'RO', 'name' => 'Romania', 'currency' => 'RON' ),
            array( 'slug' => 'RS', 'name' => 'Serbia', 'currency' => 'RSD' ),
            array( 'slug' => 'RU', 'name' => 'Russian Federation', 'currency' => 'RUB' ),
            array( 'slug' => 'RW', 'name' => 'Rwanda', 'currency' => 'RWF' ),
            array( 'slug' => 'SA', 'name' => 'Saudi Arabia', 'currency' => 'SAR' ),
            array( 'slug' => 'SB', 'name' => 'Solomon Islands', 'currency' => 'SBD' ),
            array( 'slug' => 'SC', 'name' => 'Seychelles', 'currency' => 'SCR' ),
            array( 'slug' => 'SD', 'name' => 'Sudan', 'currency' => 'SDG' ),
            array( 'slug' => 'SE', 'name' => 'Sweden', 'currency' => 'SEK' ),
            array( 'slug' => 'SG', 'name' => 'Singapore', 'currency' => 'SGD' ),
            array( 'slug' => 'SH', 'name' => 'Saint Helena', 'currency' => 'SHP' ),
            array( 'slug' => 'SI', 'name' => 'Slovenia', 'currency' => 'EUR' ),
            array( 'slug' => 'SK', 'name' => 'Slovakia', 'currency' => 'EUR' ),
            array( 'slug' => 'SL', 'name' => 'Sierra Leone', 'currency' => 'SLL' ),
            array( 'slug' => 'SM', 'name' => 'San Marino', 'currency' => 'EUR' ),
            array( 'slug' => 'SN', 'name' => 'Senegal', 'currency' => 'XOF' ),
            array( 'slug' => 'SO', 'name' => 'Somalia', 'currency' => 'SOS' ),
            array( 'slug' => 'SR', 'name' => 'Suriname', 'currency' => 'SRD' ),
            array( 'slug' => 'ST', 'name' => 'Sao Tome and Principe', 'currency' => 'STD' ),
            array( 'slug' => 'SV', 'name' => 'El Salvador', 'currency' => 'SVC' ),
            array( 'slug' => 'SX', 'name' => 'Sint Maarten (Dutch part)', 'currency' => 'NLG' ),
            array( 'slug' => 'SY', 'name' => 'Syrian Arab Republic', 'currency' => 'SYP' ),
            array( 'slug' => 'SZ', 'name' => 'Swaziland', 'currency' => 'SYP' ),
            array( 'slug' => 'TC', 'name' => 'Turks and Caicos Islands', 'currency' => 'USD' ),
            array( 'slug' => 'TD', 'name' => 'Chad', 'currency' => 'XAF' ),
            array( 'slug' => 'TG', 'name' => 'Togo', 'currency' => 'XAF' ),
            array( 'slug' => 'TH', 'name' => 'Thailand', 'currency' => 'THB' ),
            array( 'slug' => 'TJ', 'name' => 'Tajikistan', 'currency' => 'TJS' ),
            array( 'slug' => 'TK', 'name' => 'Tokelau', 'currency' => 'NZD' ),
            array( 'slug' => 'TL', 'name' => 'Timor-Leste', 'currency' => 'USD' ),
            array( 'slug' => 'TM', 'name' => 'Turkmenistan', 'currency' => 'TMT' ),
            array( 'slug' => 'TN', 'name' => 'Tunisia', 'currency' => 'TND' ),
            array( 'slug' => 'TO', 'name' => 'Tonga', 'currency' => 'TOP' ),
            array( 'slug' => 'TR', 'name' => 'Turkey', 'currency' => 'TRY' ),
            array( 'slug' => 'TT', 'name' => 'Trinidad and Tobago', 'currency' => 'TTD' ),
            array( 'slug' => 'TV', 'name' => 'Tuvalu', 'currency' => 'TVD' ),
            array( 'slug' => 'TW', 'name' => 'Taiwan', 'currency' => 'TWD' ),
            array( 'slug' => 'TZ', 'name' => 'Tanzania, United Republic of', 'currency' => 'TZS' ),
            array( 'slug' => 'UA', 'name' => 'Ukraine', 'currency' => 'UAH' ),
            array( 'slug' => 'UG', 'name' => 'Uganda', 'currency' => 'UGX' ),
            array( 'slug' => 'UM', 'name' => 'United States Minor Outlying Islands', 'currency' => 'USD' ),
            array( 'slug' => 'US', 'name' => 'United States', 'currency' => 'USD' ),
            array( 'slug' => 'UY', 'name' => 'Uruguay', 'currency' => 'UYU' ),
            array( 'slug' => 'UZ', 'name' => 'Uzbekistan', 'currency' => 'UZS' ),
            array( 'slug' => 'VA', 'name' => 'Holy See (Vatican City State)', 'currency' => 'EUR' ),
            array( 'slug' => 'VC', 'name' => 'Saint Vincent and the Grenadines', 'currency' => 'XCD' ),
            array( 'slug' => 'VE', 'name' => 'Venezuela', 'currency' => 'VEF' ),
            array( 'slug' => 'VG', 'name' => 'Virgin Islands, British', 'currency' => 'USD' ),
            array( 'slug' => 'VI', 'name' => 'Virgin Islands, U.S.', 'currency' => 'USD' ),
            array( 'slug' => 'VN', 'name' => 'Vietnam', 'currency' => 'VND' ),
            array( 'slug' => 'VU', 'name' => 'Vanuatu', 'currency' => 'VUV' ),
            array( 'slug' => 'WF', 'name' => 'Wallis and Futuna', 'currency' => 'XPF' ),
            array( 'slug' => 'WS', 'name' => 'Samoa', 'currency' => 'WST' ),
            array( 'slug' => 'YE', 'name' => 'Yemen', 'currency' => 'YER' ),
            array( 'slug' => 'YT', 'name' => 'Mayotte', 'currency' => 'EUR' ),
            array( 'slug' => 'ZA', 'name' => 'South Africa', 'currency' => 'ZAR' ),
            array( 'slug' => 'ZM', 'name' => 'Zambia', 'currency' => 'ZMW' ),
            array( 'slug' => 'ZW', 'name' => 'Zimbabwe', 'currency' => 'ZWD' )
        );

        foreach ( $country_list as $country ) {
            Country::create( array( 'name' => $country[ 'name' ], 'slug' => strtolower( $country[ 'slug' ] ), 'currency' => $country[ 'currency' ] ) );
        }
    }
}
